CREATE TABLE STUDENT (NAME VARCHAR(20),MARKS INT);
INSERT INTO STUDENT VALUES('ANU',90),('RAVI',72),('KAJAL',80);
SELECT *FROM STUDENT;
SELECT NAME,MARKS FROM STUDENT WHERE MARKS>75;
SELECT NAME,MARKS FROM STUDENT ORDER BY MARKS DESC;
SELECT MAX(MARKS) AS HIGHEST_MARKS FROM STUDENT;
SELECT AVG(MARKS) AS AVERAGE_MARKS FROM STUDENT;
SELECT COUNT(*) AS TOTAL_STUDENTS FROM STUDENT;
SELECT MARKS,COUNT(*) AS STUDENTS FROM STUDENT GROUP BY MARKS;
